language: python
dist: xenial

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=2.1
    - python: "3.4"
      env: DJANGO=2.2
    - python: "3.4"
      env: DJANGO=3
    - python: "3.5"
      env: DJANGO=3
    - python: "3.7"
      env: DJANGO=1.8
    - python: "3.7"
      env: DJANGO=1.11

install:
  - pip install tox tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      BIo7JdpiCaDZOVup44zKmyDCgQ1EiVDhoiSFo1msqIoHZYd/RVGkCFG9l4okb+tGrvm8vvCap/ZRQ6Q/Lji3GLH2ZWc499MiRxUfhixVbby77
      xjSsNeyfHSG0Cotf0sQ2WklM6rLK/qTJu472iO+bA8x5o+8TNjqSz8kzUik2rYkSEe/C09Eltfg2e8enb7SCLzcvhLwF/zfuPIEl8VzlfO3fq
      zd8yHcu/9J8O/QJUKnpNW0YTbnhnck0q1CK5Ew+tsg9Tz2Df2E5yCMqjkH8mEOPrxyWdwBlC2O7o2VVicH1LcYMJzcFSM8HhyB82oSU6LKZxh
      tJ5a2JNTTKzZr90qRtLY7efUD//y4yAUWuMjQxzOy1vUefNTv2V9mLpwBVdCaFR4WFXCw1toota/XlzZC3XOkPJTskn4Wr1BacmRAR21zfoL4
      n1t89ETG0fCoj3sN/VN9CjeZ3dQn8hSE4xmGOWUFtjzP1XsGL1THSRsxnhYn+Asmxr3OMOmchNPYIQLUJyrNucXMTYctdzidP+ahL+rDIQCVD
      TlujRWjrHVGfn3BIJ3QmY+id9YJsVrXeDQYcm8KlEUXnmcUPXnozrbM5dF94h5GCIaksx5eEZ3N+5cJN2ygZ0FIBsIEG0RJk6bVKOHh6mJrl1
      gv3LBlcatqbeimBEQwmtNc8iJMD2A=
  distributions: sdist bdist_wheel
  on:
    repo: thorgate/tg-utils
    tags: true
    python: "3.6"
    condition: "$DJANGO = 2.2"

notifications:
  email: false
